apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
        - name: simple-api
          image: dantunes/simple-api
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 20Mi
              cpu: 100m
            limits:
              memory: 20Mi
              cpu: 100m

        
    