apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: simple-api
spec:
  maxReplicas: 10
  minReplicas: 1
  targetCPUUtilizationPercentage: 50
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-api