apiVersion: v1
kind: Service
metadata:
  name: simple-api
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      name: http-svc
      targetPort: 8080
  selector:
    app: simple-api

      

  
  